### ISSUE TITLE
Invalid Github URL.

### ISSUE THREAD

**Issue by wiscaksono** [chhpt/nextjs-starter#401]
I just copy and paste the command to my terminal, here is the result: 
![image](https://user-images.githubusercontent.com/63142229/204487179-931fc7df-140a-4ed4-80e2-0e165021d6ae.png)

**Comment by ahamedzoha** [comment]
![image](https://user-images.githubusercontent.com/13367662/214206691-faadb99f-5fea-4ed5-afaa-af7617ec0661.png)
Same issue here.

**Comment by chhpt** [comment]
@wiscaksono @ahamedzoha Fixed
