### ISSUE TITLE
Enhancement : Basic layout for a application and custom layout for a page .

### ISSUE THREAD

**Issue by Easyvipin** [chhpt/nextjs-starter#466]
Idea Behind is to create a basic layout for application and provide a way to add custom layout per page. 

Basic example of this would be showing just a logo on navbar and on some other page developer can customise the navbar by adding different menu to it as per the need .

As a starter template it will set a path for developer to setup a layout ahead for application.

let me know and ill raise a PR for the same .

for reference : [Per-Page Layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts)

**Comment by Easyvipin** [comment]
Great!

**Comment by Easyvipin** [comment]
[ custom layout pr](https://github.com/chhpt/nextjs-starter/pull/470) 🚀

**Comment by chhpt** [comment]
@Easyvipin LGTM.
